class Template:
    template_paragraphs = {
       "violence" :"The respondent, [YY], must not use or threaten violence against the applicant, [XX], and must not instruct, encourage or in any way suggest that any other person should do so.",
       "intimidate":"The respondent, [YY], must not intimidate, harass or pester the applicant, [XX], and must not instruct, encourage or in any way suggest that any other person should do so.",
       "tel":"The respondent, [YY], must not telephone, text, email or otherwise contact or attempt to contact the applicant, [XX], [except for the purpose of making arrangements for contact between the respondent and the children of the family] / [except through [his]/[her] solicitors [insert name, address and telephone number]].",
       "app_prop":"The respondent, [YY], must not damage, attempt to damage or threaten to damage any property owned by or in the possession or control of the applicant, [XX], and must not instruct, encourage or in any way suggest that any other person should do so.",
       "fam_hom":"The respondent, [YY], must not damage, attempt to damage or threaten to damage the property or contents of [the family home]/[insert property], and must not instruct, encourage or in any way suggest that any other person should do so.",
       "zonal":"The respondent, [YY], must not go to, enter or attempt to enter [the family home] / [insert property] / [any property where he knows or believes the applicant, [XX], to be living], and must not go [within [insert] metres of it] / [along the road(s) known as [insert]], except that the respondent may [go to the property [without entering it]] / [go along the road(s) known as [insert]] for the purpose of collecting the children of the family for, and returning them from, such contact with the children as may be agreed in writing between the applicant and the respondent or in default of agreement ordered by the court.",
       "viol_kid":"The respondent, [YY], must not use or threaten violence against the child[ren] of the family, and must not instruct, encourage or in any way suggest that any other person should do so.",
       "intim_kid": "The respondent, [YY], must not intimidate, harass or pester the child[ren] of the family, and must not instruct, encourage or in any way suggest that any other person should do so.",
       "tel_kid": "The respondent, [YY], must not telephone, text, email or otherwise contact or attempt to contact the child[ren] of the family [except for such contact as may be agreed in writing between the applicant and the respondent or in default of agreement ordered by the court].",
       "school": "The respondent, [YY], must not [between the hours of 08:30 and 16:00] go to, enter or attempt to enter the school premises known as [insert], and must not go [within [insert] metres of it] / [along the road(s) known as [insert]], except [by prior written agreement with the applicant] / [by prior written invitation from the school authorities].",
       "duration_start":"Paragraph(s) [insert] of this order shall be effective against the respondent [YY] once it is personally served on [him]/[her] [and/or] once [he]/[she] is made aware of the terms of this order whether by personal service or otherwise.",
       "duration_end":"Paragraph(s) [insert] of this order shall last until [a further order is made] / [insert date and time] [unless before then it is varied or revoked by an order of the court].",
       "resp_discharge":"The respondent may apply to the court at any time to vary or discharge this order on [insert hours / days] [written] notice to the [applicant]/[applicant’s solicitors]. If any evidence is to be relied upon in support of [his]/[her] application, the substance of it must be communicated in writing to the [applicant]/[applicant’s solicitors] in advance.",
       "next_hearing": "The application(s) [is]/[are] listed for a further [directions] hearing in the Family Court sitting at [place] on [insert date] (‘the return date’), at which hearing the court will reconsider the application [and whether the order should continue]. If you do not attend on the date and at the time shown the court may make an order in your absence.",
       "costs": "The costs of this application are [reserved to the judge hearing the application on the return date] / [in the application], etc.",
       
       
    }